/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0050cb',
        'primary-container': '#0066ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f8f7ff',
        secondary: '#425ca0',
        'secondary-container': '#9bb4fe',
        'secondary-fixed': '#dae1ff',
        'on-secondary-fixed': '#001849',
        tertiary: '#a33200',
        'tertiary-container': '#cc4204',
        surface: '#faf8ff',
        'surface-dim': '#d8d9e6',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#ecedfa',
        'surface-container-high': '#e6e7f4',
        'surface-container-highest': '#e1e2ee',
        'surface-variant': '#e1e2ee',
        'on-surface': '#191b24',
        'on-surface-variant': '#424656',
        background: '#faf8ff',
        'on-background': '#191b24',
        outline: '#727687',
        'outline-variant': '#c2c6d8',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e303a',
        'inverse-on-surface': '#eff0fd',
        'inverse-primary': '#b3c5ff',
      },
      fontFamily: {
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
