"""add variant lineage columns

Revision ID: 59c5207a4198
Revises: 
Create Date: 2026-03-19 11:49:13.724700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c5207a4198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('parent_simulation_id', sa.String(length=36), nullable=True))
    op.add_column('simulations', sa.Column('variant_name', sa.String(length=200), nullable=True))
    op.add_column('simulations', sa.Column('changed_fields', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_simulations_parent_simulation_id'), 'simulations', ['parent_simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_parent_simulation_id'), table_name='simulations')
    op.drop_column('simulations', 'changed_fields')
    op.drop_column('simulations', 'variant_name')
    op.drop_column('simulations', 'parent_simulation_id')
    # ### end Alembic commands ###
