"""V2 world context and NPC category context dataclasses.

Layer 1 (WorldContext): Shared market reality that all NPCs already live in.
Layer 2 (NpcCategoryContext): Each NPC's pre-existing relationship with the product category.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class WorldContext:
    """Structured market context generated by the LLM for a product category.

    Represents "what an average person living in this world already knows"
    about this product category. Injected into every NPC interaction.
    """

    category_description: str = ""
    key_players: list[str] = field(default_factory=list)
    market_maturity: str = "mature"  # emerging | growing | mature | declining
    typical_price_range: str = ""
    common_purchase_triggers: list[str] = field(default_factory=list)
    common_complaints: list[str] = field(default_factory=list)
    switching_barriers: list[str] = field(default_factory=list)
    trend_awareness: list[str] = field(default_factory=list)
    social_perception: str = ""
    trust_factors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "category_description": self.category_description,
            "key_players": self.key_players,
            "market_maturity": self.market_maturity,
            "typical_price_range": self.typical_price_range,
            "common_purchase_triggers": self.common_purchase_triggers,
            "common_complaints": self.common_complaints,
            "switching_barriers": self.switching_barriers,
            "trend_awareness": self.trend_awareness,
            "social_perception": self.social_perception,
            "trust_factors": self.trust_factors,
        }

    @classmethod
    def from_dict(cls, d: dict) -> WorldContext:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @classmethod
    def default(cls) -> WorldContext:
        """Minimal fallback when LLM world-building fails."""
        return cls(
            category_description="General consumer product category.",
            key_players=[],
            market_maturity="mature",
            typical_price_range="Varies",
            common_purchase_triggers=[],
            common_complaints=[],
            switching_barriers=[],
            trend_awareness=[],
            social_perception="No specific social perception data available.",
            trust_factors=[],
        )


@dataclass
class NpcCategoryContext:
    """An individual NPC's pre-existing relationship with the product category.

    Generated by the LLM during Layer 2 enrichment. Represents what this
    specific person already uses, feels, and knows about this category
    BEFORE the product is introduced.
    """

    npc_id: str = ""
    current_solution: str = ""
    satisfaction_level: str = "neutral"  # very_satisfied | satisfied | neutral | dissatisfied | very_dissatisfied
    price_anchor: str = ""
    category_familiarity: str = "casual_user"  # unaware | heard_of_it | casual_user | regular_user | power_user
    openness_to_switch: str = "open_if_better"  # locked_in | reluctant | open_if_better | actively_looking
    personal_connection: str = ""
    pain_points: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "npc_id": self.npc_id,
            "current_solution": self.current_solution,
            "satisfaction_level": self.satisfaction_level,
            "price_anchor": self.price_anchor,
            "category_familiarity": self.category_familiarity,
            "openness_to_switch": self.openness_to_switch,
            "personal_connection": self.personal_connection,
            "pain_points": self.pain_points,
        }

    @classmethod
    def from_dict(cls, d: dict) -> NpcCategoryContext:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @classmethod
    def default(cls, npc_id: str) -> NpcCategoryContext:
        """Fallback when LLM enrichment fails for this NPC."""
        return cls(
            npc_id=npc_id,
            current_solution="Uses a generic existing solution",
            satisfaction_level="neutral",
            price_anchor="Average market price",
            category_familiarity="casual_user",
            openness_to_switch="open_if_better",
            personal_connection="No specific connection to this category",
            pain_points=[],
        )
